Attempting debug of dynamic services lookup
Also, added gitignore & gitattributes.
Package initialization failed:
CRITICAL
2014-08-11 09:47:17,161
C:\Michelle\VisTrails_SAHM\vistrails\gui\preferences.py, line 324
Initialization of package 'GeoDataPortal' failed
Package 'GeoDataPortal' failed to initialize because of the following
exceptions:
Traceback (most recent call last):
File
"C:\Michelle\VisTrails_SAHM\vistrails\core\modules\module_registry.py",
line 1524, in initialize_package
package.initialize()
File "C:\Michelle\VisTrails_SAHM\vistrails\core\modules\package.py",
line 425, in initialize
__import__(name, globals(), locals(), [])
File "C:\Michelle\VisTrails_SAHM\vistrails\core\packagemanager.py", line
256, in _import_override
return self._orig_import(name, globals, locals, fromlist, level)
File
"C:\Michelle\VisTrails_SAHM\vistrails\packages\GeoDataPortal\init.py",
line 1444, in <module>
_modules.extend(build_pyGDP_service_modules())
File
"C:\Michelle\VisTrails_SAHM\vistrails\packages\GeoDataPortal\init.py",
line 1360, in build_pyGDP_service_modules
print "new service skipped: ", service_names[dataSetURI[0]]
KeyError: 'California Basin Characterization Model Downscaled Climate
and Hydrology'